#!/bin/bash

while [[ "$#" -gt "0" ]]; do
  param=$(echo $1 | cut -d "=" -f 1)
  args=$(echo $1 | cut -d "=" -f 2)
  case $param
    --language | -l)

    ;;
    --name | -n)

    ;;
    --repo | -r)

    ;;
    --time | -t)

    ;;
    --frequency | -f)

    ;;
    
  esac
done

assign_variables $@
